package v1

import "github.com/Lands-Horizon-Corp/e-coop-server/horizon"

func Controllers(service *horizon.HorizonService) error {
	heartbeat(service)
	authenticationController(service)
	branchController(service)
	categoryController(service)
	contactController(service)
	currencyController(service)
	feedbackController(service)
	footstepController(service)
	generatedReports(service)
	invitationCode(service)
	mediaController(service)
	notificationController(service)
	organizationController(service)
	organizationDailyUsage(service)
	permissionTemplateController(service)
	qRCodeController(service)
	subscriptionPlanController(service)
	timesheetController(service)
	userController(service)
	userOrganinzationController(service)
	userRatingController(service)
	memberProfileMediaController(service)
	tagTemplateController(service)

	memberGenderController(service)
	memberCenterController(service)
	memberTypeController(service)
	memberClassificationController(service)
	memberOccupationController(service)
	memberGroupController(service)
	memberProfileController(service)

	memberEducationalAttainmentController(service)
	memberAddressController(service)
	memberContactReferenceController(service)
	memberAssetController(service)
	memberIncomeController(service)
	memberExpenseController(service)
	memberGovernmentBenefitController(service)
	memberJointAccountController(service)
	memberRelativeAccountController(service)

	bankController(service)
	cancelledCashCheckVoucherController(service)
	cashCheckVoucherController(service)
	cashCheckVoucherTagController(service)
	journalVoucherTagController(service)
	adjustmentTagController(service)
	holidayController(service)
	billAndCoinsController(service)

	transactionBatchController(service)
	cashCountController(service)
	batchFundingController(service)
	checkRemittanceController(service)
	transactionController(service)
	onlineRemittanceController(service)
	disbursementController(service)
	disbursementTransactionController(service)

	accountController(service)
	accountHistory(service)
	memberAccountingLedgerController(service)
	accountCategoryController(service)
	accountClassificationController(service)
	generalLedgerController(service)
	generalLedgerGroupingController(service)
	financialStatementController(service)
	accountTagController(service)
	paymentTypeController(service)
	paymentController(service)

	loanStatusController(service)
	loanPurposeController(service)
	loanTransactionController(service)
	loanTransactionEntryController(service)
	collateralController(service)
	computationSheetController(service)
	automaticLoanDeductionController(service)
	browseExcludeIncludeAccountsController(service)
	includeNegativeAccountController(service)
	memberDepartmentController(service)
	loanTagController(service)

	timeDepositTypeController(service)
	timeDepositComputationController(service)
	timeDepositComputationPreMatureController(service)

	chargesRateSchemeController(service)
	chargesRateByRangeOrMinimumAmountController(service)
	chargesRateSchemeModeOfPaymentController(service)
	journalVoucherController(service)
	adjustmentEntryController(service)
	companyController(service)

	organizationMediaController(service)
	fundsController(service)
	chargesRateByTermController(service)
	memberProfileArchiveController(service)
	commonController(service)
	memberProfileComaker(service)
	browseReferenceController(service)
	generateSavingsInterest(service)
	generatedSavingsInterestEntryController(service)
	mutualFundsController(service)
	mutualFundEntryController(service)
	kycController(service)
	accountTransactionController(service)
	return nil
}
