// ✅
Table media {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  account_type account_type

  description varchar(4096)
  file_name varchar(255) [not null]
  file_size integer [not null]
  file_type varchar(255) [not null]
  storage_key varchar(255) [not null]
  bucket_name varchar(255) [not null]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table branch {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  media_id varchar(50)
  type branch_type [not null, default: "cooperative branch"]
  country_code varchar(5)

  // Favorite/star
  is_main_branch boolean [not null, default: false]

  name varchar(255)
  description varchar(4096)
  address varchar(500)
  province varchar(255)
  postal_code varchar(20)
  city varchar(255)
  email varchar(255)
  region varchar(255)
  barangay varchar(255)
  contact_number varchar(15)
  is_admin_verified boolean [default: false]

  latitude decimal(10,7)
  longitude decimal(10,7)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: branch.media_id - media.id [delete:cascade]

// type of users
enum user_type {
  "employee"
  "owner"
  "member"
}

// ✅ FOR Credential login only
Table user {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  media_id varchar(50)

  password varchar(255) [not null]
  email varchar(255) [unique, not null]
  user_name varchar(255) [not null, unique]
  contact_number varchar(50) [unique, not null]
  type user_type [not null, default: "member"]

  is_email_verified boolean [not null, default: false]
  is_contact_number_verified boolean [not null, default: false]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: user.media_id - media.id [delete:cascade]

enum generated_report_status {
  pending
  started
  "in progress"
  finished
}

Table generated_report {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  requested_by_user_id varchar(50)
  media_id varchar(50)

  name varchar(255) [not null]
  description varchar(255)
  progress decimal [default: 0]
  password varchar(255)

  status generated_report_status [default: "pending"]

  started_at timestamp [not null, default: `now()`]
  finished_at timestamp

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: generated_report.media_id - media.id
Ref: generated_report.requested_by_user_id - user.id

enum account_type {
  Deposit
  Loan
  "A/R-Ledger"
  "A/R-Aging"
  Fines
  Interest
  "SVF-Ledger"
  "W-Off"
  "A/P-Ledger"
  Other
}

enum computation_type {
  "Straight"
  "Deminishing"
  "Diminishing Add-On"
  "Diminishing Yearly"
  "Diminishing Straight"
  "Diminishing Quarterly"
}

Table fines_maturity {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  account_id varchar(50)
  branch_id varchar(50)

  from integer [not null, default: 0]
  to integer [not null, default: 0]
  rate decimal [not null, default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: fines_maturity.account_id > account.id [delete:cascade, update:cascade]
Ref: fines_maturity.branch_id > branch.id [delete:cascade, update:cascade]

Table interest_maturity {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  account_id varchar(50)
  branch_id varchar(50)

  from integer [not null, default: 0]
  to integer [not null, default: 0]
  rate decimal [not null, default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: interest_maturity.account_id > account.id [delete:cascade, update:cascade]
Ref: interest_maturity.branch_id > branch.id [delete:cascade, update:cascade]

Table computation_sheet {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  branch_id varchar(50)

  name varchar(255)
  description varchar(4028)

  deliquent_account boolean [default: false] // lahat nang loan na past due
  fines_account boolean [default: false] //
  interest_account_id boolean [default: false]
  comaker_account decimal [default: 0]
  exist_account boolean [default: false]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: computation_sheet.branch_id > branch.id [delete:cascade, update:cascade]

Table include_negative_account {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  computation_sheet_id varchar(50)
  branch_id varchar(50)
  account_id varchar(50)

  description varchar(255) // just short description

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: include_negative_account.branch_id > branch.id [delete:cascade, update:cascade]
Ref: include_negative_account.account_id - account.id [delete:restrict, update:cascade]
Ref: include_negative_account.computation_sheet_id > computation_sheet.id [delete:restrict, update:cascade]

Table automatic_loan_deduction {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  account_id varchar(50)
  computation_sheet_id varchar(50)
  branch_id varchar(50)

  //CHARGES
  charges_percentage_1 decimal
  charges_percentage_2 decimal
  charges_amount decimal
  charges_divisor decimal

  min_amount decimal
  max_amount decimal

  anum integer // months , if naka 1 compute interest based number of months
  number_of_months integer
  link_account_id varchar(50)
  add_on boolean [default: false] // add onn para buo loan
  ao_rest boolean [default: false] //
  exclude_renewal boolean [default: false]
  ct integer // unknown

  name varchar(255)
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: automatic_loan_deduction.branch_id > branch.id [delete:cascade, update:cascade]
Ref: automatic_loan_deduction.computation_sheet_id > computation_sheet.id [delete: restrict, update: cascade]
Ref: automatic_loan_deduction.account_id - account.id [delete: restrict, update: cascade]
Ref: automatic_loan_deduction.link_account_id - account.id [delete:restrict, update:cascade]

Table browse_exclude_include_accounts {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  computation_sheet_id varchar(50)
  fines_account_id varchar(50)
  comaker_account_id varchar(50)
  interest_account_id varchar(50)
  deliquent_account_id varchar(50)
  include_existing_loan_account_id varchar(50)

  branch_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: browse_exclude_include_accounts.branch_id > branch.id [delete:cascade, update:cascade]
Ref: browse_exclude_include_accounts.computation_sheet_id > computation_sheet.id [delete:restrict, update:cascade]
Ref: browse_exclude_include_accounts.deliquent_account_id - account.id [delete:restrict, update:cascade]
Ref: browse_exclude_include_accounts.fines_account_id - account.id [delete:restrict, update:cascade]
Ref: browse_exclude_include_accounts.interest_account_id - account.id [delete:restrict, update:cascade]
Ref: browse_exclude_include_accounts.comaker_account_id - account.id [delete:restrict, update:cascade]
Ref: browse_exclude_include_accounts.include_existing_loan_account_id - account.id [delete:restrict, update:cascade]

// Maintenance Table
Table account_classification {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  branch_id varchar(50) [ref: - user.id]

  name varchar(255)
  description varchar(255)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: account_classification.branch_id > branch.id [delete:cascade, update:cascade]

// Maintenance Table
Table account_category {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  branch_id varchar(50) [ref: - user.id]

  name varchar(255)
  description varchar(255)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: account_category.branch_id > branch.id [delete:cascade, update:cascade]

enum lumpsum_computation_type {
  "None"
  "Compute Fines Maturity"
  "Compute Interest Maturity / Terms"
  "Compute Advance Interest"
}

enum interest_fines_computation_diminishing {
  "None"
  "By Amortization"
  "By Amortization Daly on Interest Principal + Interest = Fines(Arr)"
}

enum interest_fines_computation_diminishing_straight_diminishing_yearly {
  "None"
  "By Daily on Interest based on loan balance by year Principal + Interest Amortization = Fines Fines Grace Period Month end Amortization"
}

enum earned_unearned_interest {
  "None"
  "By Formula"
  "By Formula + Actual Pay"
  "By Advance Interest + Actual Pay"
}

enum loan_saving_type {
  "Separate"
  "Single Ledger"
  "Single Ledger if Not Zero"
  "Single Ledger Semi (15/30)"
  "Single Ledger Semi Within Maturity"
}

enum interest_deduction {
  "above"
  "Below"
}

enum other_deduction_entry {
  "None"
  "Health Care"
}

enum interest_saving_type_diminishing_straight {
  "Spread"
  "1st Payment"
}

enum other_information_of_an_account {
  "None"
  "Jewely"
  "Grocery"
  "Track Loan Deduction"
  "Restructured"
  "Cash in Bank / Cash in Check Account"
  "Cash on Hand"
}

Table account {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  general_ledger_definition_id varchar(50)
  financial_statement_definition_id varchar(50)
  branch_id varchar(50)
  account_classification_id varchar(50) [ref: - account_classification.id]
  account_category_id varchar(50) [ref: - account_category.id]
  member_type_id varchar(50)

  name varchar(255) [not null]
  description varchar(255) [not null]

  minAmount decimal [default: 0] // For deposit
  maxAmount decimal [default: 50000] // For deposit
  index integer [default: 0]
  type account_type [not null]

  // Pang Loan
  computation_type computation_type // For loan

  fines_amort decimal // For loan
  fines_maturity decimal // For loan

  interest_standard decimal // For loan
  interest_secured decimal // For loan

  computation_sheet_id varchar(50) // Scheme No in old system

  coh_cib_fines_grace_period_entry_cash_hand decimal [default: 0]
  coh_cib_fines_grace_period_entry_cash_in_bank decimal [default: 0]

  coh_cib_fines_grace_period_entry_daily_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_daily_maturity decimal [default: 0]

  coh_cib_fines_grace_period_entry_weekly_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_weekly_maturity decimal [default: 0]

  coh_cib_fines_grace_period_entry_monthly_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_monthly_maturity decimal [default: 0]

  coh_cib_fines_grace_period_entry_semi_monthly_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_semi_monthly_maturity decimal [default: 0]

  coh_cib_fines_grace_period_entry_quarterly_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_quarterly_maturity decimal [default: 0]

  coh_cib_fines_grace_period_entry_semi_anual_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_semi_anual_maturity decimal [default: 0]

  coh_cib_fines_grace_period_entry_lumpsum_amortization decimal [default: 0]
  coh_cib_fines_grace_period_entry_lumpsum_maturity decimal [default: 0]

  financial_statement_type financial_statement_type
  general_ledger_type general_ledger_type

  // interest_secured_account_id varchar(50)
  alternative_code varchar(50)

  fines_grace_period_amortization integer // number of days schedule of payment, ex: april 10, if di nakabhayad meron pang 2 days // For loan
  additional_grace_period integer //number of days
  // cut_off_days // wla muna
  // cut_off_months

  number_grace_period_daily boolean [default: false]

  fines_grace_period_maturity integer // number of days
  yearly_subscription_fee integer
  loan_cut_off_days integer

  // MGA RADIO BUTTON ENUMS

  lumpsum_computation_type lumpsum_computation_type [default: "None"] // Tska na to
  interest_fines_computation_diminishing interest_fines_computation_diminishing [default: "None"]
  interest_fines_computation_diminishing_straight_diminishing_yearly interest_fines_computation_diminishing_straight_diminishing_yearly [default: "None"]
  earned_unearned_interest earned_unearned_interest [default: "None"]
  loan_saving_type loan_saving_type [default: "Separate"] // for loan
  interest_deduction interest_deduction [default:"Above"]

  other_deduction_entry other_deduction_entry [default: "None"]
  interest_saving_type_diminishing_straight interest_saving_type_diminishing_straight [default: "Spread"]
  other_information_of_an_account other_information_of_an_account [default: "None"]

  header_row integer // Show accross all type/General
  center_row integer // Show accross all type/General
  total_row integer // Show accross all type/General

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: account.computation_sheet_id - computation_sheet.id [delete:restrict, update:restrict]
Ref: account.member_type_id - member_type.id [delete:restrict, update:restrict]
Ref: account.alternative_code - account.id [delete:restrict, update:cascade]
// Ref: account.interest_secured_account_id - account.id [delete:cascade, update:cascade]
Ref: account.branch_id > branch.id [delete:cascade, update:cascade]
Ref: account.general_ledger_definition_id > general_ledger_definition.id
Ref: account.general_ledger_definition_id > financial_statement_definition.id

// ✅
Table member_type {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  prefix varchar(255)
  name varchar(255)
  description varchar(4096)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

enum general_ledger_type {
  "Assets"
  "Liabilities, Equity & Reserves"
  "Income"
  "Expenses"
}

// NOTE: Pang report, ex: sub sub title group title
Table general_ledger_definition {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  general_ledger_definition_entries_id varchar(50)
  branch_id varchar(50)

  name varchar(255) [not null, unique]
  description varchar(4028)
  index integer [default: 0]

  name_in_total varchar(255)
  is_posting boolean [default: false]
  general_ledger_type general_ledger_type [not null]

  beginning_balance_of_the_year_credit integer [default: 0]
  beginning_balance_of_the_year_debit integer [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: general_ledger_definition.branch_id > branch.id [delete:cascade, update:cascade]
Ref: general_ledger_definition.general_ledger_definition_entries_id < general_ledger_definition.id

enum financial_statement_type {
  "Assets"
  "Liabilities"
  "Equity"
  "Revenue"
  "Expenses"
}

Table financial_statement_definition {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  financial_statement_definition_id varchar(50)
  branch_id varchar(50)

  name varchar(255) [not null, unique]
  description varchar(4028)
  index integer [default: 0]

  name_in_total varchar(255)
  is_posting boolean [default: false]
  financial_statement_type financial_statement_type

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: financial_statement_definition.branch_id > branch.id [delete:cascade, update:cascade]
Ref: financial_statement_definition.financial_statement_definition_id < financial_statement_definition.id


Table loan_status {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  name varchar(255)
  description varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table loan_guaranteed_fund {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  scheme_number integer [not null, unique]
  increasing_rate decimal [not null]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table loan_guaranteed_fund_per_month {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  month integer [default: 0]
  loan_guaranteed_fund integer [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table holidays {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  entry_date timestamp [not null]
  name varchar(255)
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table bank {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  media_id varchar(50) [ref: - media.id]

  name varchar(255) [not null]
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table payment_type {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  name varchar(255) [not null]
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table grocery_computation_sheet {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  scheme_no integer [not null, unique]
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table grocery_computation_sheet_monthly {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  grocery_computation_sheet_id varchar(50)

  months integer [default: 0]
  interest_rate decimal [default: 0]
  loan_guaranteed_fund_rate decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: grocery_computation_sheet_monthly.grocery_computation_sheet_id > grocery_computation_sheet.id [delete: restrict, update: cascade]


Table member_classification {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  name varchar(255) [not null] // ex: Bronse, Silver, Gold
  icon varchar(255)
  description varchar(4096)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp

  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
}

Table interest_rate_scheme {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  name varchar(255) [unique, not null]
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table member_classification_interest_rate {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  name varchar(255)
  description varchar(4028)

  interest_rate_scheme_id varchar(50)
  member_classification_id varchar(50)
  interest_rate_by_terms_header_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_classification_interest_rate.interest_rate_scheme_id > interest_rate_scheme.id [delete: restrict, update: cascade]
Ref: member_classification_interest_rate.member_classification_id - member_classification.id [delete: restrict, update: cascade]
Ref: member_classification_interest_rate.interest_rate_by_terms_header_id - interest_rate_by_terms_header.id [delete: restrict, update: cascade]


Table interest_rate_by_terms_header {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  member_classification_interest_rate_id varchar(50)

  header_1 integer [default: 30]
  header_2 integer [default: 60]
  header_3 integer [default: 90]
  header_4 integer [default: 120]
  header_5 integer [default: 150]
  header_6 integer [default: 180]
  header_7 integer [default: 210]
  header_8 integer [default: 240]
  header_9 integer [default: 270]
  header_10 integer [default: 300]
  header_11 integer [default: 330]
  header_12 integer [default: 360]
  header_13 integer [default: 390]
  header_14 integer [default: 410]
  header_15 integer [default: 440]
  header_16 integer [default: 470]
  header_17 integer [default: 500]
  header_18 integer [default: 530]
  header_19 integer [default: 560]
  header_20 integer [default: 590]
  header_21 integer [default: 610]
  header_22 integer [default: 640]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table interest_rate_by_term {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  name varchar(255)
  descrition varchar(4028)

  member_classification_interest_rate_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: interest_rate_by_term.member_classification_interest_rate_id > member_classification_interest_rate.id

Table interest_rate_percentage {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  name varchar(255)
  descrition varchar(4028)
  months integer [default: 0]
  interest_rate decimal [default: 0]
  member_classification_interest_rate_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: interest_rate_percentage.member_classification_interest_rate_id > member_classification_interest_rate.id


// TIME DEP
Table time_deposit_computation_header {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  header_1 integer [default: 30]
  header_2 integer [default: 60]
  header_3 integer [default: 90]
  header_4 integer [default: 120]
  header_5 integer [default: 150]
  header_6 integer [default: 180]
  header_7 integer [default: 210]
  header_8 integer [default: 240]
  header_9 integer [default: 300]
  header_10 integer [default: 330]
  header_11 integer [default: 360]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}


Table time_deposit_type {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  time_deposit_computation_header_id varchar(50)

  name varchar(255) [not null, unique]
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: time_deposit_type.time_deposit_computation_header_id - time_deposit_computation_header.id

Table time_deposit_computation {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  time_deposit_type_id varchar(50) [ref: - user.id]

  mininimum_amount decimal [default: 0]
  maximum_amount decimal [default: 0]

  header_1 decimal [default: 0]
  header_2 decimal [default: 0]
  header_3 decimal [default: 0]
  header_4 decimal [default: 0]
  header_5 decimal [default: 0]
  header_6 decimal [default: 0]
  header_7 decimal [default: 0]
  header_8 decimal [default: 0]
  header_9 decimal [default: 0]
  header_10 decimal [default: 0]
  header_11 decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: time_deposit_computation.time_deposit_type_id > time_deposit_type.id


// For deposit for paid up shared capital
Table charges_rate_scheme {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  charges_rate_by_term_header_id varchar(50)
  charges_rate_member_type_mode_of_payment_id varchar(50)

  name varchar(255) [not null, unique]
  description varchar(4028) [not null, unique]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: charges_rate_scheme.charges_rate_member_type_mode_of_payment_id - charges_rate_member_type_mode_of_payment.id
Ref: charges_rate_scheme.charges_rate_by_term_header_id - charges_rate_by_term_header.id

Table charges_rate_scheme_account {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  charges_rate_scheme_id varchar(50)
  account_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: charges_rate_scheme_account.charges_rate_scheme_id > charges_rate_scheme.id [delete:restrict, update:cascade]
Ref: charges_rate_scheme_account.account_id - account.id [delete:restrict, update:cascade]

Table charges_rate_by_range_or_minimum_amount {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  charges_rate_scheme_id archar(50)

  from decimal [default: 0]
  to decimal [default: 0]
  charge decimal [default: 0]
  amount decimal [default: 0]
  minimum_amount decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: charges_rate_by_range_or_minimum_amount.charges_rate_scheme_id > charges_rate_scheme.id [delete:restrict, update:cascade]

Table charges_rate_by_term_header {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  header_1 integer [default: 0]
  header_2 integer [default: 0]
  header_3 integer [default: 0]
  header_4 integer [default: 0]
  header_5 integer [default: 0]
  header_6 integer [default: 0]
  header_7 integer [default: 0]
  header_8 integer [default: 0]
  header_9 integer [default: 0]
  header_10 integer [default: 0]
  header_11 integer [default: 0]
  header_12 integer [default: 0]
  header_13 integer [default: 0]
  header_14 integer [default: 0]
  header_15 integer [default: 0]
  header_16 integer [default: 0]
  header_17 integer [default: 0]
  header_18 integer [default: 0]
  header_19 integer [default: 0]
  header_20 integer [default: 0]
  header_21 integer [default: 0]
  header_22 integer [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

enum charges_mode_of_payment_type {
  daily
  weekly
  monthly
  "semi-monthly"
  quarterly
  "semi-annual"
  lumpsum
}

Table charges_rate_by_term {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  charges_rate_scheme_id varchar(50)

  name varchar(255)
  description varchar(4028)
  mode_of_payment charges_mode_of_payment_type [default: "monthly"]

  rate_1 decimal [default: 0]
  rate_2 decimal [default: 0]
  rate_3 decimal [default: 0]
  rate_4 decimal [default: 0]
  rate_5 decimal [default: 0]
  rate_6 decimal [default: 0]
  rate_7 decimal [default: 0]
  rate_8 decimal [default: 0]
  rate_9 decimal [default: 0]
  rate_10 decimal [default: 0]
  rate_11 decimal [default: 0]
  rate_12 decimal [default: 0]
  rate_13 decimal [default: 0]
  rate_14 decimal [default: 0]
  rate_15 decimal [default: 0]
  rate_16 decimal [default: 0]
  rate_17 decimal [default: 0]
  rate_18 decimal [default: 0]
  rate_19 decimal [default: 0]
  rate_20 decimal [default: 0]
  rate_21 decimal [default: 0]
  rate_22 decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: charges_rate_by_term.charges_rate_scheme_id > charges_rate_scheme.id

enum charges_rate_member_type_enum {
  all
  daily
  weekly
  monthly
  "semi-monthly"
  "quarterly"
  "semi-annual"
  lumpsum
}

Table charges_rate_member_type_mode_of_payment {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  member_type_id varchar(50)

  mode_of_payment charges_rate_member_type_enum [default: 'all']

  name varchar(255)
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: charges_rate_member_type_mode_of_payment.member_type_id - member_type.id [delete:restrict, update:cascade]

Table bill_and_coins {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  media_id varchar(50)
  branch_id varchar(50)

  name varchar(255)
  value decimal [not null]
  country_code varchar(5) [not null]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: bill_and_coins.media_id - media.id [delete:cascade, update:cascade]
Ref: bill_and_coins.branch_id > branch.id [delete:restrict, update:cascade]

Table collateral {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  icon varchar(255) [ref: - user.id]

  name varchar(255) [not null]
  description varchar(4028)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Table member_type_reference {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  account_id varchar(50)

  member_type_id varchar(50)

  maintaining_balance decimal [default: 0]
  description varchar(4028)
  interest_rate decimal [default: 0]
  minimum_balance decimal [default: 0]
  charges decimal [default: 0]
  active_member_minimum_balance decimal [default: 0]
  active_member_ratio decimal [default: 0]

  other_interest_on_saving_computation_minimum_balance decimal [default:0]
  other_interest_on_saving_computation_interest_rate decimal [default:0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_type_reference.account_id - account.id [delete:restrict, update:cascade]
Ref: member_type_reference.member_type_id > member_type.id [delete:restrict, update:cascade]

Table member_type_reference_by_amount {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  member_type_reference_id varchar(50)

  from decimal [default: 0]
  to decimal [default: 0]
  rate decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_type_reference_by_amount.member_type_reference_id > member_type_reference.id [delete:cascade, update: cascade]

Table member_type_reference_interest_rate_by_ultima_membership_date {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  member_type_reference_id varchar(50)

  date_from timestamp
  date_to timestamp
  rate decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_type_reference_interest_rate_by_ultima_membership_date.member_type_reference_id > member_type_reference.id [delete:cascade, update: cascade]

Table member_type_reference_interest_rate_by_ultima_membership_date_per_year {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  member_type_reference_id varchar(50)

  year_from integer
  year_to integer
  rate decimal [default: 0]

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_type_reference_interest_rate_by_ultima_membership_date_per_year.member_type_reference_id > member_type_reference.id [delete:restrict , update: cascade]

Table general_accounting_ledger {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  employee_id varchar(50)
  member_profile_id varchar(50)

  branch_id varchar(50)
  account_id varchar(50)

  transaction_batch_id varchar(50)

  credit decimal
  debit decimal

  source varchar(255) // where this record came from

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: general_accounting_ledger.account_id > account.id [delete:restrict, update:cascade]
Ref: general_accounting_ledger.branch_id > branch.id [delete:restrict, update: cascade]
Ref: general_accounting_ledger.transaction_batch_id > transaction_batch.id [delete:restrict, update: cascade]
// TODO: To connect later member_profile_id
// Ref: general_accounting_ledger.member_profile_id > member_profile.id [delete:restrict, update:cascade]

Table account_ledger {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]
  employee_id varchar(50)
  member_profile_id varchar(50)

  branch_id varchar(50)
  account_id varchar(50)

  transaction_batch_id varchar(50)

  credit decimal
  debit decimal
  balance decimal

  source varchar(255) // where this record came from

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: account_ledger.account_id > account.id [delete:restrict, update:cascade]
Ref: account_ledger.branch_id > branch.id [delete:restrict, update: cascade]
Ref: account_ledger.transaction_batch_id > transaction_batch.id [delete:restrict, update: cascade]

Table transaction_batch {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  branch_id varchar(50)
  employee_id varchar(50)

  ending_balance decimal
  beginning_balance decimal

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: transaction_batch.employee_id > user.id
Ref: transaction_batch.branch_id > branch.id

// Table {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
  // user_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

