Table user [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

enum types_of_payment_type {
  cash
  check
  "online"
}

Table payment_type [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table transaction_batch [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table member_profile [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table branch [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table account [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table media [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table general_accounting_ledger [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table collateral [headercolor: #00FF00] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

Table loan_status [headercolor: #00FF00] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]
}

// LOAN HERE

enum loan_mode_of_payment {
  daily
  weekly
  "semi-monthly"
  monthly
  quarterly
  "semi-annual"
  lumpsum
}

enum weekdays {
  monday
  tuesday
  wednesday
  thursday
  friday
  saturday
  sunday
}

enum loan_collector_place {
  office
  field
}

enum loan_comaker_type {
  member
  deposit
  others
}

enum loan_type {
  standard
  restructured
  "standard previous"
  renewal
  "renewal without deduction"
}

enum loan_amortization_type {
  suggested
  none
}

// this is where all loan application is stored
Table loan_transaction [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  transaction_batch_id varchar(50)
  official_receipt_number varchar(255)
  loan_purpose_id varchar(50)

  loan_status_id varchar(50)

  // mode of payments
  mode_of_payment loan_mode_of_payment
  mode_of_payment_weekly weekdays // if mode of payment is set to weekly
  mode_of_payment_semi_monthly_pay_1 integer // days, if mode of payment is set to semi-monthly
  mode_of_payment_semi_monthly_pay_2 integer // days, if mode of payment is set to semi-monthly

  // Co-maker
  comaker_type loan_comaker_type
  comaker_deposit_member_accounting_ledger_id varchar(50)
  comaker_collateral_id varchar(50)
  comaker_collateral_description text

  collector_place loan_collector_place [default: "office"]

  loan_type loan_type [default: "standard"]
  // kapag restructured, meron kang existing voucher
  previous_loan_id varchar(50) // standard-cannot type, restructured-can type, only loan that are released
  terms integer [not null] // standard-cantype, restructured-cantype

  // AMORTIZATION
  amortization_amount decimal
  is_add_on boolean

  // APPLIED
  applied_1 decimal [not null] // naggapply sa account
  applied_2 decimal // nag aapply sa cashonhand

  account_id varchar(50)
  member_profile_id varchar(50)
  member_joint_account_id varchar(50) // ka may ari nang account yung gumamit/nag transact
  signature_media_id varchar(50) // Signature kung sino man nag apply nang loan

  // Clearance Analysis
  mount_to_be_closed decimal
  damayan_fund decimal
  share_capital decimal
  length_of_service varchar

  exclude_sunday boolean [default:false]
  exclude_holiday boolean [default:false]
  exclude_saturday boolean [default:false]

  // Remarks / Terms & Condition
  remarks_other_terms text
  remarks_payroll_deduction boolean [default: false]
  record_of_loan_payments_or_loan_status varchar(255)

  collateral_offered text

  // LOAN APPRAISED VALUE - this is Other/jewelry tab in old coop
  appraised_value decimal
  appraised_value_description text

  printed_date timestamp
  approved_date timestamp
  released_date timestamp // everytime na marerelease magkakaron sa transaction batch CDV History at CASH Voucher sa LESS

  // SIGNATURES
  approved_by_signature_media_id varchar(50) [ref: - media.id]
  approved_by_name varchar(255)
  approved_by_position varchar(255)

  prepared_by_signature_media_id varchar(50) [ref: - media.id]
  prepared_by_name varchar(255)
  prepared_by_position varchar(255)

  certified_by_signature_media_id varchar(50) [ref: - media.id]
  certified_by_name varchar(255)
  certified_by_position varchar(255)

  verified_by_signature_media_id varchar(50) [ref: - media.id]
  verified_by_name varchar(255)
  verified_by_position varchar(255)

  check_by_signature_media_id varchar(50) [ref: - media.id]
  check_by_name varchar(255)
  check_by_position varchar(255)

  acknowledge_by_signature_media_id varchar(50) [ref: - media.id]
  acknowledge_by_name varchar(255)
  acknowledge_by_position varchar(255)

  noted_by_signature_media_id varchar(50) [ref: - media.id]
  noted_by_name varchar(255)
  noted_by_position varchar(255)

  posted_by_signature_media_id varchar(50) [ref: - media.id]
  posted_by_name varchar(255)
  posted_by_position varchar(255)

  paid_by_signature_media_id varchar(50) [ref: - media.id]
  paid_by_name varchar(255)
  paid_by_position varchar(255)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_transaction.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_transaction.transaction_batch_id > transaction_batch.id [delete:restrict, update:cascade]
Ref: loan_transaction.comaker_deposit_member_accounting_ledger_id > member_accounting_ledger.id [delete:restrict, update:cascade]
Ref: loan_transaction.comaker_collateral_id > collateral.id [delete:restrict, update:cascade]
Ref: loan_transaction.previous_loan_id - loan_transaction.id [delete:restrict, update:cascade]
Ref: loan_transaction.loan_purpose_id > loan_purpose.id [delete:restrict, update:cascade]
Ref: loan_transaction.loan_status_id > loan_status.id [delete:restrict, update:cascade]

Table loan_clearance_analysis [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)

  regular_deduction_description text
  regular_deduction_amount decimal

  balances_description text
  balancces_amount decimal
  balances_count integer

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_clearance_analysis.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_clearance_analysis.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]

Table loan_clearance_analysis_institution [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)

  name varchar(50)
  description text

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_clearance_analysis_institution.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_clearance_analysis_institution.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]

Table loan_comaker_member [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  member_profile_id varchar(50)
  loan_transaction_id varchar(50)

  description text // name / collateral
  amount decimal
  months_count integer
  year_count decimal

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_comaker_member.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_comaker_member.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]
Ref: loan_comaker_member.member_profile_id > member_profile.id [delete:restrict, update:cascade]

Table loan_transaction_entry [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)

  description text

  credit decimal
  debit decimal

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_transaction_entry.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_transaction_entry.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]

Table loan_tag [headercolor: #00ff26] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)

  name varchar(50)
  description text
  category tag_category
  color varchar(20)
  icon varchar(20)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_tag.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_tag.loan_transaction_id > loan_transaction.id [delete:cascade, update:cascade]

Table loan_terms_and_condition_suggested_payment [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_terms_and_condition_suggested_payment.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_terms_and_condition_suggested_payment.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]
// Ref: loan_terms_and_condition_suggested_payment.account_id > account.id [delete:restrict, update:cascade]

Table loan_terms_and_condition_amount_receipt [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50) // payment sa account na ito

  account_id varchar(50) // payment sa account na ito
  amount decimal //

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_terms_and_condition_amount_receipt.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_terms_and_condition_amount_receipt.loan_transaction_id > loan_transaction.id [delete:cascade, update:cascade]
Ref: loan_terms_and_condition_amount_receipt.account_id > account.id [delete:cascade, update:cascade]

// NOTE: This is maintenance table that wwwould reflect to all loan entry/application
Table loan_purpose [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  description text
  icon varchar(255)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_purpose.branch_id > branch.id [delete:cascade, update:cascade]

Table loan_ledger [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)
  cash_voucher_id varchar(50)
  count integer

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_ledger.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_ledger.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]


Table loan_notes [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  loan_transaction_id varchar(50)

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: loan_notes.branch_id > branch.id [delete:cascade, update:cascade]
Ref: loan_notes.loan_transaction_id > loan_transaction.id [delete:restrict, update:cascade]

Table member_accounting_ledger [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  member_profile_id varchar(50)
  account_id varchar(50)

  count integer
  balance decimal
  interest decimal
  fines decimal
  due decimal
  carried_forward_due decimal //are u sure?
  stored_value_facility decimal
  principal_due decimal
  last_pay timestamp

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_accounting_ledger.branch_id > branch.id [delete:cascade, update:cascade]
Ref: member_accounting_ledger.account_id > account.id [delete:cascade, update:cascade]
Ref: member_accounting_ledger.member_profile_id > member_profile.id [delete:cascade, update:cascade]

Table member_loan_ledger [headercolor: #ff0000] {
  id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  branch_id varchar(50)
  created_by_id varchar(50) [ref: - user.id]
  updated_by_id varchar(50) [ref: - user.id]
  deleted_by_id varchar(50) [ref: - user.id]

  member_profile_id varchar(50)
  account_id varchar(50)

  count integer
  balance decimal
  interest decimal
  fines decimal
  due decimal
  carried_forward_due decimal //are u sure?
  stored_value_facility decimal
  principal_due decimal
  last_pay timestamp

  created_at timestamp [not null, default: `now()`]
  updated_at timestamp [not null, default: `now()`]
  deleted_at timestamp
}

Ref: member_loan_ledger.branch_id > branch.id [delete:cascade, update:cascade]
Ref: member_loan_ledger.account_id > account.id [delete:cascade, update:cascade]
Ref: member_loan_ledger.member_profile_id > member_profile.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]

// Table [headercolor: #ff0000] {
  // id varchar(50) [primary key, unique, default: `uuid_generate_v4()`]

  // branch_id varchar(50)
  // created_by_id varchar(50) [ref: - user.id]
  // updated_by_id varchar(50) [ref: - user.id]
  // deleted_by_id varchar(50) [ref: - user.id]

  // created_at timestamp [not null, default: `now()`]
  // updated_at timestamp [not null, default: `now()`]
  // deleted_at timestamp
// }

// // Ref: .branch_id > branch.id [delete:cascade, update:cascade]
