name: Deploy to Development

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Deploy to Server
      env:
        HOST: ${{ secrets.LINODE_HOST }}
        USER: ${{ secrets.LINODE_USER }}
        APP_DIR: "/home/user/coop-server/development"  # Update this path
      run: |
        ssh -t $USER@$HOST << 'EOF'
        set -e
        # Install dependencies if missing
        command -v go &> /dev/null || sudo apt-get install -y golang
        command -v tmux &> /dev/null || sudo apt-get install -y tmux
        command -v git &> /dev/null || sudo apt-get install -y git

        # Create/maintain app directory
        mkdir -p $APP_DIR
        cd $APP_DIR

        # Clone or pull latest code
        if [ ! -d ".git" ]; then
          git clone https://github.com/Lands-Horizon-Corp/e-coop-server.git .
        fi
        
        git checkout development
        git pull origin development

        # Build and restart application
        go build -o main
        tmux kill-session -t ecoop-dev &> /dev/null || true
        tmux new-session -d -s ecoop-dev
        tmux send-keys -t ecoop-dev './main' C-m

        echo "Development deployment completed!"
        EOF