name: Deploy to Linode (Development)

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.LINODE_KNOWN_HOST }}

    - name: Deploy to Linode
      env:
        HOST: ${{ secrets.LINODE_HOST }}
        USER: ${{ secrets.LINODE_USER }}
      run: |
        ssh -t $USER@$HOST << 'EOF'
          set -e
          cd ./ || { echo "Directory not found"; exit 1; }

          # Kill existing tmux session
          tmux kill-session -t goapp || true

          # Pull latest changes
          git pull

          # Run Go tests
          echo "Running tests..."
          go test -v ./services/horizon_test || { echo "Tests failed"; exit 1; }

          # Build the Go binary
          echo "Building application..."
          go build -o app .

          # Create new tmux session to run app
          tmux new-session -d -s goapp "./app"

          echo "Golang deployment completed successfully"
        EOF
