name: Deploy to Linode (Development)

on:
  push:
    branches: [ development ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key and known_hosts
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.LINODE_KNOWN_HOST }}

    - name: Deploy to Linode
      env:
        HOST: ${{ secrets.LINODE_HOST }}
        USER: ${{ secrets.LINODE_USER }}
      run: |
        ssh -t -o StrictHostKeyChecking=yes $USER@$HOST << 'EOF'
            set -e

            # Make sure the directory exists and cd into it (adjust path as needed)
            mkdir -p /root   # or your app directory
            cd /root || { echo "Directory not found"; exit 1; }

            # Kill existing tmux session if exists
            if tmux has-session -t goapp 2>/dev/null; then
                tmux kill-session -t goapp
            fi  

            # Pull latest code changes
            git pull || { echo "Git pull failed"; exit 1; }

            # Run Go tests and exit if failed
            echo "Running tests..."
            go test -v ./services/horizon_test || { echo "Tests failed"; exit 1; }

            # Build the Go binary and exit if failed
            echo "Building application..."
            go build -o app . || { echo "Build failed"; exit 1; }

            # Start the app in a detached tmux session
            tmux new-session -d -s goapp "./app"

            echo "Golang deployment completed successfully"
        EOF
