name: Deploy Go App to Linode

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.LINODE_SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}

    - name: Setup and Deploy
      env:
        HOST: ${{ secrets.LINODE_HOST }}
        USER: ${{ secrets.LINODE_USER }}
        APP_DIR: "/home/cooperative/development"  # Update this path
        REPO_URL: "https://github.com/Lands-Horizon-Corp/e-coop-server.git"
      run: |
        ssh -t $USER@$HOST << EOF
        set -e
        # Install dependencies
        sudo apt-get update
        sudo apt-get install -y git tmux golang

        # Create app directory
        mkdir -p $APP_DIR
        cd $APP_DIR

        # Clone or pull repository
        if [ ! -d ".git" ]; then
          git clone $REPO_URL .
        else
          git pull origin main
        fi

        # Build Go binary
        go build -o main

        # Restart application
        tmux kill-session -t development-server || true
        tmux new-session -d -s development-server
        tmux send-keys -t development-server './main' C-m

        echo "Deployment completed successfully!"
        EOF